pipeline{

    parameters{
        choice(name: 'terraformAction',choices: ['apply','destroy'],description: 'Choose your terraform action to perform')
    }


    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages{
        stage('checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/abdullasd14301/Opskillsup.git'
            }
        }

        stage('plan'){
            steps{
                sh '''
                    pwd
                    cd 04-PROJECT-1/
                    terraform init
                    terraform plan -out tfplan
                    terraform show -no-color tfplan > tfplan.txt
                '''
            }
        }

        stage('Approval'){
            steps{
                script{
                    def plan = readFile '04-PROJECT-1/tfplan.txt'

                    input(
                        message: "Do you want to procede with the terraform actions..?",
                        parameters: [
                            text(name: 'planReview',description: 'Can you review your code',defaultValue: plan)
                        ]

                    )
                }
            }
        }

        stage('Apply or Destroy'){
            when{
                expression{
                    return params.terraformAction =='apply' || params.terraformAction == 'destroy'
                }
            }

            steps{
                script{
                    if (params.terraformAction =='apply') {
                        sh "cd 04-PROJECT-1; terraform apply -input=false tfplan"
                    } else if (params.terraformAction =='destroy') {
                        sh "cd 04-PROJECT-1; terraform destroy -auto-approve"
                    }
                
                }
            }
        }
    }

}
